#!/bin/sh

DIRNAME="tropmat"

noexp=(
copyright
make_tarball

apps/tom/rules/flips.rules
apps/tom/rules/blow_up.rules
apps/tom/src/hidden.cc
apps/tom/src/vertices_from_topes_nongen.cc
apps/tom/src/perl/wrap-hidden.cc
apps/tom/src/perl/wrap-vertices_from_topes_nongen.cc
)

svn export . $DIRNAME

for i in "${noexp[@]}"; do rm $DIRNAME/$i; done;

tar -cvzf $DIRNAME.tar.gz $DIRNAME
rm -rf $DIRNAME
